### ISSUE TITLE
Not available in VSCodium

### ISSUE THREAD

**Issue by mathieu0c** [jkearins/vscode-action-buttons#2]
Hi !

Unfortunately, your extension is not available for VSCodium due to the usage of [open-vsx](https://open-vsx.org/)

Could it be possible for you to publish your extension to this website as well please?

Procedure is documented on the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by jkearins** [comment]
Hi, [mathieu0c](https://github.com/mathieu0c)
I will take a look at open-vsx.
