### ISSUE TITLE
Set UID as variable in command

### ISSUE THREAD

**Issue by leonp5** [jkearins/vscode-action-buttons#4]
Hello,

how can i set the current user id as variable in the command?

```
"commands": [
	{
		"cwd": "${workspaceFolder}/.docker",
		"name": "DComposeUpBuild",
		"color": "white",
		"command": "CURRENT_UID=$(id -u):82 docker compose --env-file ./../.env up -d --build",
		"terminalName": "ActionButtons"
	},
],
```

This is the way i would do it if i start the command in the terminal. But when i trigger the action button i get the message that `CURRENT_UID` is not set.
How can i pass it correct to the command?

I'm using a linux machine with VSCodium.

Thank you :-)

**Comment by jkearins** [comment]
Hi leonp5, try to add `export` before the var:
```
"command": "export CURRENT_UID=$(id -u):82 docker compose --env-file ./../.env up -d --build",
```
Maybe it will help.

**Comment by leonp5** [comment]
Thanks for the answer.

It works the way I wrote. The mistake was at another point.
